import getServerSession from '@/lib/getServerSession'
import '../styles/globals.css'
import ClientSessionProvider from './client-session'
import { Session } from 'next-auth'
import { ThemeProvider } from '@/components/theme-provider'

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

const RootLayout = async ({ children }: { children: React.ReactNode }) => {
    const session: Session = await getServerSession()

    return (
        <html lang="en">
            <body>
                <ClientSessionProvider session={session}>
                    <ThemeProvider
                        attribute="class"
                        defaultTheme="light"
                        enableSystem
                        disableTransitionOnChange
                    >
                        {children}
                    </ThemeProvider>
                </ClientSessionProvider>
            </body>
        </html>
    )
}

export default RootLayout
