import getServerSession from '@/lib/getServerSession'
import '../styles/globals.css'
import ClientSessionProvider from './client-session'

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

const RootLayout = async ({ children }: { children: React.ReactNode }) => {
    const session = await getServerSession()

    return (
        <html lang="en">
            <body>
                <ClientSessionProvider session={session}>
                    {children}
                </ClientSessionProvider>
            </body>
        </html>
    )
}

export default RootLayout
